### ISSUE TITLE
Assets Not Loading

### ISSUE THREAD

**Issue by tgandee79** [shamsup/remix-starter-serverless#7]
I'm still having an issue, and I'm not sure if it's related to this repo or general Serverless knowledge and integration with AWS / S3.  

I followed all the instructions with this repo to deploy the basic app to AWS. I made all the config switches for `OriginCustomHeaders` and `custom::dev::host` after the first deploy.  

I am still getting `404` errors on the assets for remix and `.ico` files for the example code.  Is there something on the AWS side I need to do?  I tried granting `everyone` permissions for `list` and `read`.  

![image](https://user-images.githubusercontent.com/1489134/217276188-ed657797-2d4b-466e-b592-9957f284a155.png)

**Comment by shamsup** [comment]
You should be accessing the site through the CloudFront distribution instead of the API gateway URL - I see the `execute-api.us-east-1.amazonaws.com` endpoint as the document. This should be something like `abcdefghij.cloudfront.net` instead.

CloudFront is doing the routing between API Gateway and the S3 bucket in this template instead of API Gateway routing between Lambda and S3.
